steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.frontend'
      - '-t'
      - 'asia-south1-docker.pkg.dev/lokesh-ai-portfolio/ai-portfolio-images/workflow-agent-frontend:latest'
      - '.'

images:
  - 'asia-south1-docker.pkg.dev/lokesh-ai-portfolio/ai-portfolio-images/workflow-agent-frontend:latest'
