FROM python:3.11-slim

WORKDIR /app

COPY requirements-frontend.txt .

RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY frontend ./frontend

CMD streamlit run frontend/app.py --server.address=0.0.0.0 --server.port=${PORT:-8080} --server.headless=true
